FROM node:18-alpine

ENV TOKEN="eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiI5NDQ0IiwiZHQiOiIyMDIzMTIxOSJ9.a3-mHjqwiAWFdHMgp1zDmT4CduTN1EjW2_uzvNPDRtg"
ENV APP_ID="10770"
ENV CLIENT_SECRET="9aed18458a6428deaa3388aee189d1ffe81a0c72b22adbb6"
ENV POSTGRESQL_HOST=""
ENV POSTGRESQL_PORT=""
ENV POSTGRESQL_USER=""
ENV POSTGRESQL_PASSWORD=""
ENV POSTGRESQL_DATABASE=""
ENV POSTGRESQL_SCHEMA=""
ENV URL_CALLBACK="https://api-onlog-nuvemshop.com.br"

ENV WORK_PATH /usr/share/node/api/onlog-nuvemshop

WORKDIR $WORK_PATH

COPY . $WORK_PATH

EXPOSE 3000

CMD [ "node", "src/app.js" ]